### ISSUE TITLE
Make a official release

### ISSUE THREAD

**Issue by leitao** [Libvecpf/libvecpf#1]
I am working to include this lib in Debian and unfortunately it doesn't have a release yet. Can you please make a release?

Github would do it if automatically if you use vX.Y tags in the git repository.

**Comment by ryanarn** [comment]
On Apr 1, 2015 1:00 PM, "Breno Leitao" notifications@github.com wrote:

> I am working to include this lib in Debian and unfortunately it doesn't
> have a release yet. Can you please make a release?
> 
> Github would do it if automatically if you use vX.Y tags in the git
> repository.
> 
> —
> Reply to this email directly or view it on GitHub.

Adhemerval, do you still have the ability to be an administrator on this
project?  I'm not sure if I do.  One of us can probably create the release.

**Comment by ryanarn** [comment]
This project is now showing up in the one I have access in github.

On Fri, Apr 3, 2015 at 12:55 AM, Ryan S. Arnold ryan.arnold@gmail.com wrote:

> On Apr 1, 2015 1:00 PM, "Breno Leitao" notifications@github.com wrote:
> 
> > I am working to include this lib in Debian and unfortunately it doesn't
> > have a release yet. Can you please make a release?
> > 
> > Github would do it if automatically if you use vX.Y tags in the git
> > repository.
> > 
> > —
> > Reply to this email directly or view it on GitHub.
> 
> Adhemerval, do you still have the ability to be an administrator on this
> project?  I'm not sure if I do.  One of us can probably create the release.

## 

“One thing I have learned in a long life: that all our science,
measured against reality, is primitive and childlike -- and yet it is
the most precious thing we have.”

― Albert Einstein

**Comment by tuliom** [comment]
Ryan, don't make a release yet, please.
I'm still integrating more fixes and new features and Breno is already aware about this.

**Comment by ryanarn** [comment]
On Mon, Apr 6, 2015, 7:00 AM Tulio Magno Quites Machado Filho <
notifications@github.com> wrote:

Ryan, don't make a release yet, please.
I'm still integrating more fixes and new features and Breno is already
aware about this.

—
Reply to this email directly or view it on GitHub
https://github.com/Libvecpf/libvecpf/issues/1#issuecomment-90028895.<img
src="
https://ci5.googleusercontent.com/proxy/FC-6PjGXrkPodVJXngB7FCHFvWTwj27tSSKqFDOB-QzkshPQDnObxPu0m4sLuEgRPjYebpgZTLBRB1Lom7Vn0x_SV9CY3JM_ZA6AjI4YX74Qiet8p6vZ_EGIb9i9IhtWklnitBRRQ3BN-X9T5R45Cd-mvpuRnA=s0-d-e1-ft#https://github.com/notifications/beacon/ABEiRdikwchhSaguvFb0wMj0Rl0L30G7ks5n8mzHgaJpZM4D4qDp.gif
">

Tulio, sure. I can help when you're ready.

**Comment by tuliom** [comment]
This should be fixed now: https://github.com/Libvecpf/libvecpf/releases/tag/v1.1.0
Thanks!
